sudo: required

services:
  - docker

jdk:
  - oraclejdk8

language: java
script: travis_wait 60 ./gradlew clean build

os:
  - linux
notifications:
  email:
    on_success: change
    on_failure: always
